#!/usr/bin/env bash

# lets be paranoid for a bit
set -e
if [[ -n $p1_debug ]]; then
  set -x
fi

# print everything to stderr so it can be easily filtered out
# with p1 <args> 2>/dev/null
prnt()
{
  echo $* 1>&2
}

# "asynchronously" remove tmp file injected into browser context
cleanUp()
{
  sleep 7
  rm $1 || true

}
if [[ -z $1 ]]; then
  echo "Please provide a path to your 1Password.agilekeychain"
  echo "Example:"
  echo "If you 1Password.agilekeychain file is in Dropbox/1password"
  echo "then invoke p1 with:"
  echo "    p1 ~/Dropbox/1password"
  exit 1
fi


# detect which mktemp we're dealing with
# and create a temporary file with .js extension
makeTmpFile ()
{
  local t_path=''
  t_path=$(mktemp -t p1 -q)
  if [[ $? == 1 ]] ; then
    t_path=$(mktemp)
  fi

  if [[ $? == 1 ]]; then
    echo'no mktemp!'
    exit 1
  fi

  echo "$t_path.js"
}

t_file=$(makeTmpFile)
printf 'Enter your 1password Master Password: '
# mask user input
stty_orig=`stty -g` stty -echo
read master_pass
stty $stty_orig >/dev/null

echo "PASSWORD='$master_pass';" > $t_file

#... and we're back to normal mode
prnt 'ok... logging you in'

# ok, don't stop the script at this point because we will run in
# all sorts of problems if we don't cleanup after ourselves

set +e

# phantom js has 7 seconds to start and load stuff
cleanUp $t_file &
phantomjs src/p1.js $t_file $1 out.png

# propagate js script exit status for greater justice
exit $?
