#!/usr/bin/env bash
set -e
if [[ -n $p1_debug ]]; then
  set -x

fi


# detect which mktemp we're dealing with
# and create a temporary file with .js extension
__TmpFile ()
{
  local t_path=''
  t_path=$(mktemp -t p1 -q)
  if [[ $? == 1 ]] ; then
    t_path=$(mktemp)
  fi

  if [[ $? == 1 ]]; then
    echo 'no mktemp!'
    exit 1
  fi

  echo "$t_path.js"
}

# create tmp file

t_file=$(__TmpFile)
echo 'Enter your 1password Master Password:'
# mask user input
stty_orig=`stty -g` stty -echo
read master_pass
stty $stty_orig >/dev/null

echo "PASSWORD='$master_pass';" > $t_file

#... and we're back to normal mode
echo 'ok... logging you in'
phantomjs src/p1.js $t_file out.png
__phantom_exit_status=$?

# whatevs
rm $t_file || true

exit $__phantom_exit_status
